# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging
from typing import List

import torch
import triton
import triton.language as tl

from flag_gems.utils import tl_extra_shim

logger = logging.getLogger(__name__)


@triton.jit
def _amp_foreach_non_finite_check_and_unscale_kernel(
    inp_ptr,
    inv_scale_ptr,
    output_ptr,
    num_elements,
    BLOCK_SIZE: tl.constexpr,
):
    pid = tl.program_id(0)
    block_start = pid * BLOCK_SIZE
    offsets = tl.arange(0, BLOCK_SIZE)
    mask = block_start + offsets < num_elements

    # Load the input value
    inp = tl.load(inp_ptr + block_start + offsets, mask=mask, other=0.0)

    # Load the inv_scale value
    scale = tl.load(inv_scale_ptr)

    # Convert to float32 for computation to handle float16/bfloat16
    inp_fp32 = inp.to(tl.float32)
    scale_fp32 = scale.to(tl.float32)

    # Check for non-finite values (inf or nan) using float32
    is_non_finite = ~tl_extra_shim.finitef(inp_fp32)

    # Scale the values: only finite values are scaled
    # Non-finite values stay as-is (in original dtype)
    scaled_fp32 = tl.where(is_non_finite, inp_fp32, inp_fp32 * scale_fp32)

    # Convert back to original dtype
    # We need to determine the output dtype from the input pointer
    # For now, assume input dtype is preserved
    scaled = scaled_fp32.to(inp.dtype)

    # Store the result
    tl.store(output_ptr + block_start + offsets, scaled, mask=mask)


def _amp_foreach_non_finite_check_and_unscale_(
    tensors: List[torch.Tensor],
    found_inf: torch.Tensor,
    inv_scale: torch.Tensor,
):
    """
    Check for non-finite values in tensors and unscale them.

    For each tensor in the list:
    - Scale finite values by inv_scale
    - Non-finite values (inf, nan) remain unchanged

    If any tensor has non-finite values, set found_inf to 1.0.
    """
    logger.debug("GEMS AMP_FOREACH_NON_FINITE_CHECK_AND_UNSCALE")

    if not isinstance(tensors, (list, tuple)):
        raise TypeError(f"Expected list or tuple of tensors, got {type(tensors)}")

    if len(tensors) == 0:
        return

    # Ensure inv_scale is a float32 tensor as PyTorch expects
    inv_scale = inv_scale.to(dtype=torch.float32)

    # Process each tensor in the list
    for tensor in tensors:
        if not tensor.is_floating_point():
            # Skip non-floating point tensors
            continue

        num_elements = tensor.numel()
        if num_elements == 0:
            continue

        # Allocate output tensor (in-place operation)
        output = torch.empty_like(tensor)

        # 1024 offers a good balance of occupancy and parallelism for typical gradient tensor sizes
        BLOCK_SIZE = 1024
        grid = (triton.cdiv(num_elements, BLOCK_SIZE),)

        _amp_foreach_non_finite_check_and_unscale_kernel[grid](
            tensor,
            inv_scale,
            output,
            num_elements,
            BLOCK_SIZE=BLOCK_SIZE,
        )

        # Copy output back to input (in-place)
        tensor.copy_(output)

    # Check if any tensor has non-finite values
    # This needs to be done after scaling since scaling might produce inf from overflow
    for tensor in tensors:
        if not tensor.is_floating_point():
            continue

        if tensor.is_complex():
            # Check real and imaginary parts separately
            if not torch.all(torch.isfinite(tensor.real)) or not torch.all(
                torch.isfinite(tensor.imag)
            ):
                found_inf.fill_(1.0)
                return
        else:
            if not torch.all(torch.isfinite(tensor)):
                found_inf.fill_(1.0)
                return
