# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn
from flag_gems.utils import libentry, libtuner
from flag_gems.utils import triton_lang_extension as tle

logger = logging.getLogger(__name__)


# Simple fixed configs for sparse semi-structured mm
SPARSE_MM_CONFIGS = [
    triton.Config(
        {"BLOCK_SIZE_M": 32, "BLOCK_SIZE_N": 32, "BLOCK_SIZE_K": 32},
        num_stages=3,
        num_warps=4,
    ),
]


@libentry()
@libtuner(
    configs=SPARSE_MM_CONFIGS,
    key=["M", "N", "K4"],
)
@triton.jit
def sparse_semi_structured_mm_kernel(
    A,
    Meta,
    B,
    C,
    M,
    N,
    K4,
    stride_am,
    stride_ak,
    stride_mm,
    stride_mn,
    stride_bk,
    stride_bn,
    stride_cm,
    stride_cn,
    BLOCK_SIZE_M: tl.constexpr,
    BLOCK_SIZE_N: tl.constexpr,
    BLOCK_SIZE_K: tl.constexpr,
):
    """
    Kernel for sparse semi-structured matrix multiplication.

    A: (M, 4*K4) - dense matrix with 2:4 sparsity pattern
    Meta: (M, K4) - boolean mask indicating which 2 elements in each group of 4 are valid
    B: (4*K4, N) - dense matrix
    C: (M, N) - output matrix

    For each group of 4 elements in A's K dimension:
    - Meta[i, k] = True: use A[i, 4k] and A[i, 4k+1]
    - Meta[i, k] = False: use A[i, 4k+2] and A[i, 4k+3]
    """
    pid = tle.program_id(0)
    num_pid_n = tl.cdiv(N, BLOCK_SIZE_N)

    # Combine pid_m and pid_n into a single pid
    pid_m = pid // num_pid_n
    pid_n = pid % num_pid_n

    offs_am = pid_m * BLOCK_SIZE_M + tl.arange(0, BLOCK_SIZE_M)
    offs_bn = pid_n * BLOCK_SIZE_N + tl.arange(0, BLOCK_SIZE_N)
    offs_k = tl.arange(0, BLOCK_SIZE_K)

    # Calculate the actual K dimension
    K = K4 * 4

    # Initialize accumulator
    accumulator = tl.zeros((BLOCK_SIZE_M, BLOCK_SIZE_N), dtype=tl.float32)

    num_iters = tl.cdiv(K4, BLOCK_SIZE_K)

    # Loop over K dimension in blocks
    for k in range(num_iters):
        k_offset = k * BLOCK_SIZE_K

        # Load meta for this K block
        meta_ptrs = Meta + (
            offs_am[:, None] * stride_mm + (offs_k + k_offset)[None, :] * stride_mn
        )

        # Create a 2D mask: (BLOCK_SIZE_M, BLOCK_SIZE_K)
        mask_2d = offs_am[:, None] < M
        mask_2d = mask_2d & ((offs_k + k_offset)[None, :] < K4)

        meta = tl.load(meta_ptrs, mask=mask_2d, other=0)

        # Load all 4 A elements for each K position
        # A0: elements at positions 4k
        a0_ptrs = A + (
            offs_am[:, None] * stride_am
            + (offs_k * 4 + k_offset * 4 + 0)[None, :] * stride_ak
        )
        mask_a = (offs_am[:, None] < M) & ((offs_k * 4 + k_offset * 4 + 0)[None, :] < K)
        a0 = tl.load(a0_ptrs, mask=mask_a, other=0.0)

        # A1: elements at positions 4k+1
        a1_ptrs = A + (
            offs_am[:, None] * stride_am
            + (offs_k * 4 + k_offset * 4 + 1)[None, :] * stride_ak
        )
        mask_a = (offs_am[:, None] < M) & ((offs_k * 4 + k_offset * 4 + 1)[None, :] < K)
        a1 = tl.load(a1_ptrs, mask=mask_a, other=0.0)

        # A2: elements at positions 4k+2
        a2_ptrs = A + (
            offs_am[:, None] * stride_am
            + (offs_k * 4 + k_offset * 4 + 2)[None, :] * stride_ak
        )
        mask_a = (offs_am[:, None] < M) & ((offs_k * 4 + k_offset * 4 + 2)[None, :] < K)
        a2 = tl.load(a2_ptrs, mask=mask_a, other=0.0)

        # A3: elements at positions 4k+3
        a3_ptrs = A + (
            offs_am[:, None] * stride_am
            + (offs_k * 4 + k_offset * 4 + 3)[None, :] * stride_ak
        )
        mask_a = (offs_am[:, None] < M) & ((offs_k * 4 + k_offset * 4 + 3)[None, :] < K)
        a3 = tl.load(a3_ptrs, mask=mask_a, other=0.0)

        # Load B elements similarly
        # B0: elements at positions 4k
        b0_ptrs = B + (
            (offs_k * 4 + k_offset * 4 + 0)[:, None] * stride_bk
            + offs_bn[None, :] * stride_bn
        )
        mask_b = ((offs_k * 4 + k_offset * 4 + 0)[:, None] < K) & (offs_bn[None, :] < N)
        b0 = tl.load(b0_ptrs, mask=mask_b, other=0.0)

        b1_ptrs = B + (
            (offs_k * 4 + k_offset * 4 + 1)[:, None] * stride_bk
            + offs_bn[None, :] * stride_bn
        )
        mask_b = ((offs_k * 4 + k_offset * 4 + 1)[:, None] < K) & (offs_bn[None, :] < N)
        b1 = tl.load(b1_ptrs, mask=mask_b, other=0.0)

        b2_ptrs = B + (
            (offs_k * 4 + k_offset * 4 + 2)[:, None] * stride_bk
            + offs_bn[None, :] * stride_bn
        )
        mask_b = ((offs_k * 4 + k_offset * 4 + 2)[:, None] < K) & (offs_bn[None, :] < N)
        b2 = tl.load(b2_ptrs, mask=mask_b, other=0.0)

        b3_ptrs = B + (
            (offs_k * 4 + k_offset * 4 + 3)[:, None] * stride_bk
            + offs_bn[None, :] * stride_bn
        )
        mask_b = ((offs_k * 4 + k_offset * 4 + 3)[:, None] < K) & (offs_bn[None, :] < N)
        b3 = tl.load(b3_ptrs, mask=mask_b, other=0.0)

        # Compute contribution for this K block
        # Use element-wise multiplication with masking instead of tl.where
        # When meta is 1: accumulate a0*b0 + a1*b1
        # When meta is 0: accumulate a2*b2 + a3*b3

        # Compute all 4 products using element-wise broadcasting

        # Let's do this more carefully:
        # For each (m, n), the result is sum over k of:
        #   if meta[m, k]: a0[m,k]*b0[k,n] + a1[m,k]*b1[k,n]
        #   else: a2[m,k]*b2[k,n] + a3[m,k]*b3[k,n]

        # We can compute this as:
        #   sum(meta[m,k] * (a0[m,k]*b0[k,n] + a1[m,k]*b1[k,n]) +
        #       (1-meta[m,k]) * (a2[m,k]*b2[k,n] + a3[m,k]*b3[k,n]))

        # Expand meta for computation
        meta_exp = meta[:, :, None]  # (BM, BK, 1)

        # Compute products per K position
        # prod00[m,k,n] = a0[m,k] * b0[k,n], etc.
        # These have shape (BM, BK, BN)
        prod00_exp = a0[:, :, None] * b0[None, :, :]
        prod01_exp = a1[:, :, None] * b1[None, :, :]
        prod02_exp = a2[:, :, None] * b2[None, :, :]
        prod03_exp = a3[:, :, None] * b3[None, :, :]

        # Apply meta mask and sum over K
        # When meta is 1: keep prod00 + prod01
        # When meta is 0: keep prod02 + prod03
        selected = (prod00_exp + prod01_exp) * meta_exp + (prod02_exp + prod03_exp) * (
            1 - meta_exp
        )
        accumulator += tl.sum(selected, axis=1)

    # Store result
    c_ptrs = C + stride_cm * offs_am[:, None] + stride_cn * offs_bn[None, :]
    c_mask = (offs_am[:, None] < M) & (offs_bn[None, :] < N)
    tl.store(c_ptrs, accumulator, mask=c_mask)


def _sparse_semi_structured_mm(mat1, mat1_meta, mat2, *, out_dtype=None):
    """
    Performs a sparse semi-structured matrix multiplication.

    Args:
        mat1: Dense matrix of shape (M, 4*K) with 2:4 sparsity pattern
        mat1_meta: Boolean mask of shape (M, K) indicating which elements are valid
        mat2: Dense matrix of shape (4*K, N)
        out_dtype: Optional output dtype

    Returns:
        Matrix of shape (M, N)
    """
    logger.debug("GEMS SPARSE_SEMI_STRUCTURED_MM")

    M = mat1.shape[0]
    K4 = mat1_meta.shape[1]
    N = mat2.shape[1]

    # Validate shapes
    assert mat1.shape == (
        M,
        4 * K4,
    ), f"Expected mat1 shape ({M}, {4 * K4}), got {mat1.shape}"
    assert mat2.shape == (
        4 * K4,
        N,
    ), f"Expected mat2 shape ({4 * K4}, {N}), got {mat2.shape}"
    assert mat1_meta.shape == (
        M,
        K4,
    ), f"Expected mat1_meta shape ({M}, {K4}), got {mat1_meta.shape}"

    # Determine output dtype
    if out_dtype is not None:
        output_dtype = out_dtype
    else:
        output_dtype = mat1.dtype

    out = torch.empty((M, N), device=mat1.device, dtype=output_dtype)

    grid = lambda META: (
        triton.cdiv(M, META["BLOCK_SIZE_M"]) * triton.cdiv(N, META["BLOCK_SIZE_N"]),
        # This is intentionally a 1D grid, we handle pid_m/pid_n decomposition inside
    )

    with torch_device_fn.device(mat1.device):
        sparse_semi_structured_mm_kernel[grid](
            mat1,
            mat1_meta,
            mat2,
            out,
            M,
            N,
            K4,
            mat1.stride(0),
            mat1.stride(1),
            mat1_meta.stride(0),
            mat1_meta.stride(1),
            mat2.stride(0),
            mat2.stride(1),
            out.stride(0),
            out.stride(1),
        )

    return out


# Reference implementation for testing
def _sparse_semi_structured_mm_ref(mat1, mat1_meta, mat2):
    """
    Reference implementation using pure PyTorch.
    This is used for testing correctness.
    """
    M, K4 = mat1_meta.shape
    N = mat2.shape[1]

    # Reshape mat1 to (M, K4, 4)
    mat1_reshaped = mat1.view(M, K4, 4)

    # Reshape mat2 to (K4, 4, N)
    mat2_reshaped = mat2.view(K4, 4, N)

    # Create meta mask: for each (m, k), if meta[m,k] is True, keep pos 0,1, else keep pos 2,3
    meta_mask = torch.cat(
        [
            mat1_meta.unsqueeze(2),
            mat1_meta.unsqueeze(2),
            (~mat1_meta).unsqueeze(2),
            (~mat1_meta).unsqueeze(2),
        ],
        dim=2,
    )

    # Apply mask to mat1_reshaped
    mat1_masked = torch.where(meta_mask, mat1_reshaped, torch.zeros_like(mat1_reshaped))

    # Compute result with masked values
    result = torch.zeros((M, N), dtype=mat1.dtype, device=mat1.device)
    for pos in range(4):
        a = mat1_masked[:, :, pos]  # (M, K4)
        b = mat2_reshaped[:, pos, :]  # (K4, N) - FIX: correct indexing
        result += torch.mm(a, b)

    return result
