# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch

logger = logging.getLogger(__name__)


def _thnn_fused_lstm_cell_backward_impl(
    grad_hy: torch.Tensor,
    grad_cy: torch.Tensor,
    cx: torch.Tensor,
    cy: torch.Tensor,
    workspace: torch.Tensor,
    has_bias: bool,
):
    """Compute gradients for fused LSTM cell.

    This FlagGems implementation uses pure PyTorch tensor operations for
    numerically correct gradient computation.

    Args:
        grad_hy: Gradient of hidden output (batch, hidden_size)
        grad_cy: Gradient of cell state (batch, hidden_size)
        cx: Cell state input (batch, hidden_size)
        cy: Cell state output after tanh (batch, hidden_size)
        workspace: Workspace tensor from forward pass (batch, 4*hidden_size)
                   containing sigmoid/tanh gate activations for i, f, g, o.
        has_bias: Whether bias is used

    Returns:
        Tuple of (grad_input_gates, grad_cx, grad_biases)
    """
    logger.debug("GEMS _THNN_FUSED_LSTM_CELL_BACKWARD_IMPL")

    batch_size, hidden_size = cx.shape

    # Ensure contiguous
    grad_hy = grad_hy.contiguous()
    grad_cy = grad_cy.contiguous()
    cx = cx.contiguous()
    cy = cy.contiguous()
    workspace = workspace.contiguous()

    # Extract gate activations from workspace
    # worksapce layout: [i_gate, f_gate, g_gate, o_gate] along dim=1
    i_gate = workspace[:, :hidden_size]
    f_gate = workspace[:, hidden_size : 2 * hidden_size]
    g_gate = workspace[:, 2 * hidden_size : 3 * hidden_size]
    o_gate = workspace[:, 3 * hidden_size : 4 * hidden_size]

    # Compute gradients via chain rule
    # d(cy)/d(inputs) = dL/dhy * o * (1 - tanh^2(cy)) + dL/dcy
    tanh_cy = torch.tanh(cy)
    d_cy = grad_hy * o_gate * (1.0 - tanh_cy * tanh_cy) + grad_cy

    # Gate gradients
    grad_i = d_cy * g_gate * i_gate * (1.0 - i_gate)
    grad_f = d_cy * cx * f_gate * (1.0 - f_gate)
    grad_g = d_cy * i_gate * (1.0 - g_gate * g_gate)
    grad_o = grad_hy * tanh_cy * o_gate * (1.0 - o_gate)

    grad_input_gates = torch.cat([grad_i, grad_f, grad_g, grad_o], dim=1)

    # grad_cx
    grad_cx = d_cy * f_gate

    # Bias gradient
    if has_bias:
        grad_biases = grad_input_gates.sum(dim=0)
    else:
        grad_biases = torch.zeros(0, dtype=cx.dtype, device=cx.device)

    return grad_input_gates, grad_cx, grad_biases
