# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging
from typing import Optional, Tuple

import torch
import triton
import triton.language as tl

from flag_gems.runtime import device, torch_device_fn

logger = logging.getLogger(__name__)


# Simple backward kernel - each thread handles one output position
@triton.jit
def _upsample_nearest_exact2d_backward_kernel(
    grad_output_ptr,
    grad_input_ptr,
    N,
    C,
    OH,
    OW,
    IH,
    IW,
    reciprocal_scale_h: tl.constexpr,
    reciprocal_scale_w: tl.constexpr,
    BLOCK_SIZE: tl.constexpr,
):
    # Get program IDs
    pid = tl.program_id(0)
    nc_pid = tl.program_id(1)

    # Each thread handles one output position
    # Total output positions = OH * OW
    idx = pid * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE)

    # Filter valid indices
    mask = idx < (OH * OW)

    # Compute oh, ow from linear index
    ow = idx % OW
    oh = idx // OW

    # Compute corresponding input indices
    ih = (oh * reciprocal_scale_h).to(tl.int32)
    iw = (ow * reciprocal_scale_w).to(tl.int32)

    # Clamp to valid range
    ih = tl.minimum(ih, IH - 1)
    iw = tl.minimum(iw, IW - 1)

    # Compute offsets
    # For output: (nc, oh, ow) -> linear
    # For input: (nc, ih, iw) -> linear
    offset_o = (nc_pid * OH + oh) * OW + ow
    offset_i = (nc_pid * IH + ih) * IW + iw

    # Load gradient and accumulate
    grad = tl.load(grad_output_ptr + offset_o, mask=mask)
    tl.atomic_add(grad_input_ptr + offset_i, grad, mask=mask)


def _upsample_nearest_exact2d_backward(
    grad_output: torch.Tensor,
    output_size: Tuple[int, int],
    input_size: Tuple[int, int, int, int],
    scales_h: Optional[float] = None,
    scales_w: Optional[float] = None,
) -> torch.Tensor:
    logger.debug("GEMS _UPSAMPLE_NEAREST_EXACT2D_BACKWARD")

    assert grad_output.device.type == device.name
    assert grad_output.ndim == 4, "The ndim of grad_output must be 4"
    assert len(output_size) == 2, "The len of output_size must be 2"
    assert len(input_size) == 4, "The len of input_size must be 4"

    OH, OW = output_size
    N, C, IH, IW = input_size

    # Validate grad_output shape matches output_size
    assert grad_output.shape == (N, C, OH, OW), (
        f"grad_output shape {grad_output.shape} does not match "
        f"expected shape (N={N}, C={C}, OH={OH}, OW={OW})"
    )

    # Compute scales - use same formula as forward pass
    if scales_h is not None:
        reciprocal_scale_h = 1 / scales_h
    else:
        reciprocal_scale_h = IH / OH
    if scales_w is not None:
        reciprocal_scale_w = 1 / scales_w
    else:
        reciprocal_scale_w = IW / OW

    # Allocate output (grad_input) internally as float32 because
    # tl.atomic_add does not support bf16; converted back at the end.
    grad_input = torch.zeros(
        (N, C, IH, IW), device=grad_output.device, dtype=torch.float32
    )

    # Grid: each (n,c) pair is a separate block in Y dimension
    # Each thread in X dimension handles one output position
    BLOCK = 128
    grid = (triton.cdiv(OH * OW, BLOCK), N * C)

    with torch_device_fn.device(grad_output.device):
        _upsample_nearest_exact2d_backward_kernel[grid](
            grad_output,
            grad_input,
            N,
            C,
            OH,
            OW,
            IH,
            IW,
            reciprocal_scale_h,
            reciprocal_scale_w,
            BLOCK,
        )

    return grad_input.to(grad_output.dtype)
