# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems import runtime
from flag_gems.utils import libentry

logger = logging.getLogger(__name__)


@libentry()
@triton.autotune(
    configs=runtime.get_tuned_config("adaptive_max_pool3d_backward"),
    key=["n_elements"],
    reset_to_zero=["grad_input_ptr"],
)
@triton.jit
def adaptive_max_pool3d_backward_kernel(
    grad_output_ptr,
    indices_ptr,
    grad_input_ptr,
    # Shapes
    in_n,
    in_c,
    in_d,
    in_h,
    in_w,
    out_d,
    out_h,
    out_w,
    n_elements: tl.constexpr,
    BLOCK_SIZE: tl.constexpr,
):
    pid = tl.program_id(0)
    block_start = pid * BLOCK_SIZE
    offsets = block_start + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements

    # Compute (n, c, d_out, h_out, w_out) from flat offset
    # Total output elements per n,c is out_d * out_h * out_w
    out_per_nc = out_d * out_h * out_w

    # Flatten 5D position to 1D and then reconstruct
    # output position = offsets[i]
    # n = position // out_per_nc  (but actually position is already in range [0, n_elements))
    # But n_elements = in_n * in_c * out_per_nc
    # So we need to decode: position = ((n * in_c + c) * out_d + d_out) * out_h * out_w + h_out * out_w + w_out

    nc_out = offsets // out_per_nc
    remainder = offsets % out_per_nc
    d_out = remainder // (out_h * out_w)
    remainder2 = remainder % (out_h * out_w)
    h_out = remainder2 // out_w
    w_out = remainder2 % out_w

    # n = nc_out // in_c, c = nc_out % in_c
    n_idx = nc_out // in_c
    c_idx = nc_out % in_c

    # Load indices for these output positions
    # output is laid out as (n, c, d_out, h_out, w_out) with contiguous strides for last 3 dims
    # So offset = n * in_c * out_per_nc + c * out_per_nc + d_out * out_h * out_w + h_out * out_w + w_out
    out_offset = (
        n_idx * in_c * out_per_nc
        + c_idx * out_per_nc
        + d_out * out_h * out_w
        + h_out * out_w
        + w_out
    )

    idx = tl.load(indices_ptr + out_offset, mask=mask, other=0)

    # Convert flat index to 3D position in input (D, H, W)
    # idx = d_in * in_h * in_w + h_in * in_w + w_in
    spatial_size = in_h * in_w
    d_in = idx // spatial_size
    remainder = idx % spatial_size
    h_in = remainder // in_w
    w_in = remainder % in_w

    # Load gradient at output position
    grad_val = tl.load(grad_output_ptr + out_offset, mask=mask, other=0.0)

    # Compute offset for input grad position
    # Input is laid out as (n, c, d_in, h_in, w_in)
    in_offset = (
        n_idx * in_c * in_d * in_h * in_w
        + c_idx * in_d * in_h * in_w
        + d_in * in_h * in_w
        + h_in * in_w
        + w_in
    )

    # Atomically accumulate gradient at the corresponding input position.
    # Atomic add is required because multiple output positions within the
    # adaptive pooling window can map to the same input position when input
    # spatial dims are not evenly divisible by the output size.
    tl.atomic_add(grad_input_ptr + in_offset, grad_val, mask=mask)


def adaptive_max_pool3d_backward(
    grad_output: torch.Tensor,
    self: torch.Tensor,
    indices: torch.Tensor,
):
    logger.debug("GEMS ADAPTIVE_MAX_POOL3D_BACKWARD")

    in_n, in_c, in_d, in_h, in_w = self.shape
    out_d, out_h, out_w = (
        grad_output.shape[2],
        grad_output.shape[3],
        grad_output.shape[4],
    )

    grad_input = torch.zeros_like(self, dtype=torch.float32)

    if grad_input.numel() == 0:
        return grad_input.to(grad_output.dtype)

    n_elements = in_n * in_c * out_d * out_h * out_w

    grid = lambda meta: (triton.cdiv(n_elements, meta["BLOCK_SIZE"]),)

    adaptive_max_pool3d_backward_kernel[grid](
        grad_output,
        indices,
        grad_input,
        in_n,
        in_c,
        in_d,
        in_h,
        in_w,
        out_d,
        out_h,
        out_w,
        n_elements,
    )

    return grad_input.to(grad_output.dtype)
