# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

from flag_gems.utils import broadcastable_to

logger = logging.getLogger(__name__)

from flag_gems.ops.addmm import addmm  # noqa: E402


def addmm_(self, mat1, mat2, *, beta=1, alpha=1):
    assert self.dtype.is_floating_point, "Only floating-point dtypes are supported"
    assert mat1.shape[1] == mat2.shape[0], "Incompatible dimensions"
    assert broadcastable_to(
        self.shape, (mat1.shape[0], mat2.shape[1])
    ), "Incompatible input shape"

    logger.debug("GEMS ADDMM_")
    result = addmm(self, mat1, mat2, beta=beta, alpha=alpha)
    return self.copy_(result)
