# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import triton
import triton.language as tl

from flag_gems.utils import pointwise_dynamic, tl_extra_shim

_ASIN = tl_extra_shim.asin
logger = logging.getLogger(__name__)


@pointwise_dynamic(promotion_methods=[(0, "INT_TO_FLOAT")])
@triton.jit()
def arcsin_kernel(x):
    # Match torch.arcsin by evaluating in float32 before casting back.
    return _ASIN(x.to(tl.float32))


def arcsin(x, *, out=None):
    logger.debug("GEMS ARCSIN FORWARD")
    if out is None:
        return arcsin_kernel(x)
    arcsin_kernel(x, out0=out)
    return out


def arcsin_(x):
    logger.debug("GEMS ARCSIN INPLACE")
    arcsin_kernel(x, out0=x)
    return x


def arcsin_out(x, *, out=None):
    logger.debug("GEMS ARCSIN OUT")
    return arcsin(x, out=out)
