# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn

logger = logging.getLogger(__name__)


@triton.jit
def channel_shuffle_kernel(
    in_ptr,
    out_ptr,
    n_elements,
    N,
    C,
    H,
    W,
    groups,
    C_out,
    BLOCK_SIZE: tl.constexpr,
):
    pid = tl.program_id(axis=0)
    block_start = pid * BLOCK_SIZE
    offsets = block_start + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements

    # Strides for contiguous NCHW
    sN_in = C * H * W
    sC_in = H * W
    sH_in = W

    sN_out = C * H * W
    sC_out = H * W
    sH_out = W
    sW_out = 1

    # Decode input linear index into (n, c, h, w)
    n = offsets // sN_in
    rem1 = offsets - n * sN_in
    c = rem1 // sC_in
    rem2 = rem1 - c * sC_in
    h = rem2 // sH_in
    w = rem2 - h * sH_in

    # Channel shuffle: divide into groups and rearrange
    # Original: (n, c, h, w) where c in [0, C)
    # After reshape to (n, groups, C//groups, h, w):
    #   group_id = c // (C // groups) = c * groups // C
    #   channel_in_group = c % (C // groups)
    # After transpose to (n, C//groups, groups, h, w):
    #   new channel = channel_in_group * groups + group_id
    c_per_group = C // groups
    group_id = c // c_per_group
    channel_in_group = c - group_id * c_per_group
    new_c = channel_in_group * groups + group_id

    # Compute output linear index
    out_index = n * sN_out + new_c * sC_out + h * sH_out + w * sW_out

    x = tl.load(in_ptr + offsets, mask=mask)
    tl.store(out_ptr + out_index, x, mask=mask)


def channel_shuffle(input: torch.Tensor, groups: int) -> torch.Tensor:
    logger.debug("GEMS CHANNEL_SHUFFLE")
    x = input
    if not x.is_contiguous():
        x = x.contiguous()

    # Channel shuffle expects (*, C, H, W) where C is divisible by groups
    if x.ndim < 3:
        raise ValueError(
            f"Input must have at least 3 dimensions (C, H, W), got {x.ndim}"
        )

    N, C, H, W = x.shape[-4:]
    g = int(groups)
    assert g > 0, "groups must be > 0"
    assert C % g == 0, f"C ({C}) must be divisible by groups ({g})"

    out = torch.empty_like(x)
    n_elements = x.numel()
    if n_elements == 0:
        return out

    # 1024 is a common choice balancing occupancy and register pressure for element-wise kernels
    BLOCK_SIZE = 1024
    grid = lambda META: (triton.cdiv(n_elements, META["BLOCK_SIZE"]),)
    with torch_device_fn.device(x.device):
        channel_shuffle_kernel[grid](
            x,
            out,
            n_elements,
            N,
            C,
            H,
            W,
            g,
            C,
            BLOCK_SIZE=BLOCK_SIZE,
        )
    return out
