# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

logger = logging.getLogger(__name__)


@triton.jit
def dequantize_kernel(
    x, scale, zero_point, output, n_elements, BLOCK_SIZE: tl.constexpr
):
    pid = tl.program_id(axis=0)
    block_start = pid * BLOCK_SIZE
    offsets = block_start + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements
    x_val = tl.load(x + offsets, mask=mask, other=0).to(tl.float32)
    result = (x_val - zero_point) * scale
    tl.store(output + offsets, result, mask=mask)


def dequantize(a):
    """Dequantize a quantized tensor.

    Args:
        a: A quantized tensor (e.g., torch.qint8, torch.quint8)

    Returns:
        A float32 tensor with the dequantized values
    """
    logger.debug("GEMS DEQUANTIZE")

    # Get quantized tensor info
    int_repr = a.int_repr().to(a.device)
    scale = float(a.q_scale())
    zero_point = int(a.q_zero_point())

    output = torch.empty(int_repr.shape, dtype=torch.float32, device=a.device)
    n_elements = output.numel()
    # Power-of-2 block size for coalesced memory access in element-wise dequantization
    BLOCK_SIZE = 1024
    grid = (triton.cdiv(n_elements, BLOCK_SIZE),)

    dequantize_kernel[grid](int_repr, scale, zero_point, output, n_elements, BLOCK_SIZE)
    return output
