# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton

from flag_gems.utils import pointwise_dynamic

logger = logging.getLogger(__name__)


@pointwise_dynamic(is_tensor=[True], promotion_methods=[(0, "DEFAULT")])
@triton.jit
def copy_func(x):
    return x


def diagonal_copy(
    self: torch.Tensor, offset: int = 0, dim1: int = 0, dim2: int = 1
) -> torch.Tensor:
    """
    Performs the same operation as torch.diagonal, but returns a copy instead of a view.
    """
    logger.debug("GEMS DIAGONAL_COPY")

    # Validate dimensions
    ndim = self.ndim
    dim1 = dim1 if dim1 >= 0 else dim1 + ndim
    dim2 = dim2 if dim2 >= 0 else dim2 + ndim

    if dim1 == dim2:
        raise ValueError("dim1 and dim2 must be different")

    # Use torch.diagonal to get a view of the diagonal
    # Then use pointwise_dynamic to create a copy
    diag_view = torch.diagonal(self, offset=offset, dim1=dim1, dim2=dim2)

    # Clone to create a copy (this ensures it's not a view)
    # Use pointwise_dynamic to invoke a Triton kernel
    output = torch.empty_like(diag_view)

    if output.numel() == 0:
        return output

    overload = copy_func.instantiate(diag_view.ndim)
    overload(diag_view, out0=output)

    return output
