# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import triton
import triton.language as tl

from flag_gems.utils import pointwise_dynamic, tl_extra_shim

logger = logging.getLogger(__name__)


_ERFINV = tl_extra_shim.erfinv


@pointwise_dynamic(promotion_methods=[(0, "DEFAULT")])
@triton.jit
def erfinv_func(x):
    return _ERFINV(x.to(tl.float32))


def erfinv(x):
    logger.debug("GEMS ERFINV")
    return erfinv_func(x)


def erfinv_(x):
    logger.debug("GEMS ERFINV_")
    erfinv_func(x, out0=x)
    return x
