# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging
from typing import Sequence

import torch

logger = logging.getLogger(__name__)


def expand(inp: torch.Tensor, size: Sequence[int]) -> torch.Tensor:
    """Expand tensor to specified size.

    This is a zero-copy view operation that broadcasts dimensions with size 1
    by setting their stride to 0.
    """
    logger.debug("GEMS EXPAND")

    # Normalize sizes to be a list
    input_shape = list(inp.shape)
    original_input_ndim = len(input_shape)
    size = list(size)

    if len(size) < original_input_ndim:
        raise RuntimeError(
            "expand: the number of sizes provided must be greater or equal "
            f"to the number of dimensions in the tensor ({original_input_ndim})"
        )

    # Prepend 1s if size has more dimensions than input
    if len(size) > original_input_ndim:
        input_shape = [1] * (len(size) - original_input_ndim) + input_shape
        inp = inp.view(input_shape)

    leading_dims = len(size) - original_input_ndim

    # Replace -1 with actual size from input
    for i in range(len(size)):
        if size[i] == -1:
            if i < leading_dims:
                raise RuntimeError(
                    f"The expanded size of the tensor ({size[i]}) isn't allowed "
                    f"in a leading, non-existing dimension {i}"
                )
            size[i] = input_shape[i]
        elif size[i] < 0:
            raise RuntimeError(
                f"The expanded size of the tensor ({size[i]}) is invalid"
            )
        elif size[i] != input_shape[i] and input_shape[i] != 1:
            raise RuntimeError(
                "The expanded size of the tensor "
                f"({size[i]}) must match the existing size ({input_shape[i]}) "
                f"at non-singleton dimension {i}"
            )

    # Compute target strides:
    # - If target size > source size (broadcasting), stride = 0
    # - Otherwise, use the source dimension's stride
    input_strides = list(inp.stride())
    strides = []
    for i in range(len(size)):
        if input_shape[i] == 1 and size[i] != 1:
            # Broadcasting dimension, stride = 0
            strides.append(0)
        else:
            # Use source stride
            strides.append(input_strides[i])

    # Use as_strided to create a view with the new shape and strides
    # This is a meta-information operation, no actual data is copied
    return torch.as_strided(inp, size, strides)


def expand_(inp: torch.Tensor, size: Sequence[int]) -> torch.Tensor:
    """In-place expand (for compatibility, returns view)."""
    logger.debug("GEMS EXPAND_")
    return expand(inp, size)
