# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import logging

import torch
import triton
import triton.language as tl

from flag_gems.ops.randn import randn_kernel
from flag_gems.runtime import torch_device_fn
from flag_gems.utils import pointwise_dynamic
from flag_gems.utils.random_utils import philox_backend_seed_offset
from flag_gems.utils.shape_utils import volume

logger = logging.getLogger(__name__)
UNROLL = 4


@pointwise_dynamic(
    is_tensor=[True, False, False], promotion_methods=[(0, 1, 2, "DEFAULT")]
)
@triton.jit
def log_normal_transform(val, mean, std):
    # Log-normal distribution: exp(N(mean, std))
    # If X ~ N(mean, std), then exp(X) ~ logNormal(mean, std)
    return tl.exp(val * std + mean)


def log_normal_distribution(
    shape, device, dtype, mean, std, *, generator=None, out=None
):
    if out is None:
        out = torch.empty(shape, device=device, dtype=dtype)
    N = volume(shape)
    grid_fn = lambda meta: (triton.cdiv(N, meta["BLOCK"] * UNROLL),)

    increment = triton.cdiv(N, UNROLL)
    philox_seed, philox_offset = philox_backend_seed_offset(
        increment, generator=generator
    )
    # Generate float32 normal first, then transform and convert to target dtype
    temp_out = torch.empty(shape, device=device, dtype=torch.float32)
    with torch_device_fn.device(device):
        randn_kernel[grid_fn](temp_out, N, philox_seed, philox_offset)

    # Transform to log-normal and store in output
    log_normal_transform(temp_out, mean, std, out0=out)
    return out


def log_normal_(self, mean=1.0, std=2.0, *, generator=None):
    logger.debug("GEMS LOG_NORMAL_")
    shape = self.shape
    device = self.device
    dtype = self.dtype

    # Generate log-normal distribution in-place
    log_normal_distribution(
        shape, device, dtype, mean, std, generator=generator, out=self
    )
    return self
