# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.utils import pointwise_dynamic

logger = logging.getLogger(__name__)


@pointwise_dynamic(
    is_tensor=[True, True, False, False],
    num_outputs=2,
    promotion_methods=[
        (0, 1, "DEFAULT"),
        (0, 1, "DEFAULT"),
    ],
)
@triton.jit
def rrelu_with_noise_forward(self, noise, lower, upper):
    # RReLU: if x >= 0: out = x, else: out = x * noise
    # noise is pre-generated uniform random in [lower, upper]
    out = tl.where(self >= 0, self, self * noise)
    return out, noise


def rrelu_with_noise_functional(
    self,
    noise,
    lower=0.125,
    upper=0.33333333333333331,
    training=False,
    generator=None,
):
    logger.debug("GEMS RRELU_WITH_NOISE_FUNCTIONAL")
    return _rrelu_with_noise_impl(self, noise, lower, upper, training, generator)


def _rrelu_with_noise_impl(self, noise, lower, upper, training, generator):
    assert noise.shape == self.shape, "noise tensor must have the same shape as self"
    assert generator is None, "generator is not supported in FlagGems"

    if not training:
        slope = (lower + upper) * 0.5
        noise_tmp = torch.full_like(self, slope)
        output = rrelu_with_noise_forward(self, noise_tmp, lower, upper)
        return output[0], noise
    else:
        output = rrelu_with_noise_forward(self, noise, lower, upper)
        return output
