# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

logger = logging.getLogger(__name__)


@triton.jit
def _soft_margin_loss_backward_kernel(
    grad_output_ptr,
    self_ptr,
    target_ptr,
    out_ptr,
    n_elements,
    reduction: tl.constexpr,
    n_elements_reduced: tl.constexpr,
    BLOCK_SIZE: tl.constexpr,
):
    pid = tl.program_id(axis=0)
    block_start = pid * BLOCK_SIZE
    offsets = block_start + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements

    grad_output = tl.load(grad_output_ptr + offsets, mask=mask, other=0.0)
    self_vals = tl.load(self_ptr + offsets, mask=mask, other=0.0)
    target = tl.load(target_ptr + offsets, mask=mask, other=0.0)

    # Cast to float32 for computation
    grad_output_f = grad_output.to(tl.float32)
    self_f = self_vals.to(tl.float32)
    target_f = target.to(tl.float32)

    # Backward formula: grad_output * (-target) / (1 + exp(target * self))
    exp_term = tl.exp(target_f * self_f)
    grad = grad_output_f * (-target_f) / (1.0 + exp_term)

    # Apply mean reduction if needed
    if reduction == 1:
        # reduction == 1 means 'mean'
        grad = grad / n_elements_reduced

    tl.store(out_ptr + offsets, grad, mask=mask)


def _normalize_reduction(reduction):
    # Accept both string and enum/int forms: 0=none, 1=mean, 2=sum
    if isinstance(reduction, str):
        r = reduction.lower()
        if r == "none":
            return 0
        if r == "mean":
            return 1
        if r == "sum":
            return 2
        raise ValueError(f"Invalid reduction: {reduction}")
    if isinstance(reduction, int):
        if reduction in (0, 1, 2):
            return reduction
        raise ValueError(f"Invalid reduction int: {reduction}")
    raise ValueError(f"Unsupported reduction type: {type(reduction)}")


def _check_tensors(
    grad_output: torch.Tensor, self_tensor: torch.Tensor, target: torch.Tensor
):
    if not (self_tensor.device == target.device == grad_output.device):
        raise AssertionError(
            "soft_margin_loss_backward: all tensors must be on the same device."
        )
    if not (self_tensor.numel() == target.numel() == grad_output.numel()):
        raise AssertionError(
            "soft_margin_loss_backward: grad_output, self, and target must have the same number of elements."
        )
    if not self_tensor.is_contiguous():
        self_tensor = self_tensor.contiguous()
    if not target.is_contiguous():
        target = target.contiguous()
    if not grad_output.is_contiguous():
        grad_output = grad_output.contiguous()
    return grad_output, self_tensor, target


def soft_margin_loss_backward(
    grad_output: torch.Tensor,
    self_tensor: torch.Tensor,
    target: torch.Tensor,
    reduction="mean",
):
    logger.debug("GEMS SOFT_MARGIN_LOSS_BACKWARD")
    grad_output, self_tensor, target = _check_tensors(grad_output, self_tensor, target)

    n_elements = self_tensor.numel()
    red = _normalize_reduction(reduction)

    if n_elements == 0:
        return torch.empty_like(self_tensor)

    out = torch.empty_like(self_tensor)
    # Power-of-2 block size balancing occupancy and parallelism for H20.
    BLOCK_SIZE = 1024
    grid = lambda meta: (triton.cdiv(n_elements, meta["BLOCK_SIZE"]),)

    _soft_margin_loss_backward_kernel[grid](
        grad_output,
        self_tensor,
        target,
        out,
        n_elements,
        red,
        n_elements,
        BLOCK_SIZE=BLOCK_SIZE,
    )
    return out
