# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.utils import pointwise_dynamic, tl_extra_shim

logger = logging.getLogger(__name__)


@pointwise_dynamic(promotion_methods=[(0, 1, "INT_TO_FLOAT")])
@triton.jit
def shifted_chebyshev_polynomial_u_kernel(x, n):
    # Shifted Chebyshev polynomial of the second kind: U_n^*(x)
    # Formula: U_n^*(x) = sin((n+1) * arccos(2x-1)) / sin(arccos(2x-1))
    # Where the shifted polynomial is defined on [0, 1]

    # Convert to float32 for computation, then convert back
    x_f32 = x.to(tl.float32)
    n_f32 = n.to(tl.float32)

    x_shifted = x_f32 * 2.0 - 1.0

    # Clamp to valid range for acos to avoid numerical issues
    x_shifted = tl.where(x_shifted > 1.0, 1.0, x_shifted)
    x_shifted = tl.where(x_shifted < -1.0, -1.0, x_shifted)

    acos_val = tl_extra_shim.acos(x_shifted)
    sin_acos = tl_extra_shim.sin(acos_val)

    # Handle boundary conditions where sin(acos_val) is close to 0
    # At x=0: x_shifted=-1, acos_val=pi, sin=0, limit = (-1)^n * (n+1)
    # At x=1: x_shifted=1, acos_val=0, sin=0, limit = (n+1)
    near_boundary = tl.abs(sin_acos) < 1e-6

    # Calculate boundary values based on position
    # x_shifted < 0 means x < 0.5
    # Check if n is odd using modulo for floats: n % 2 = n - 2 * floor(n/2)
    n_mod_2 = n_f32 - 2.0 * tl_extra_shim.floor(n_f32 / 2.0)
    is_odd = tl.abs(n_mod_2 - 1.0) < 0.5  # n is odd if n % 2 is close to 1

    boundary_val = tl.where(
        x_shifted < 0.0,
        tl.where(is_odd, -1.0 - n_f32, n_f32 + 1.0),  # at x=0: (-1)^n * (n+1)
        n_f32 + 1.0,  # at x=1: (n+1)
    )

    # Regular calculation using the trigonometric formula
    numerator = tl_extra_shim.sin((n_f32 + 1.0) * acos_val)
    result = numerator / sin_acos

    # Select boundary or regular value
    result = tl.where(near_boundary, boundary_val, result)

    # Convert back to original dtype
    return result.to(x.dtype)


# Kernel for scalar n (n is not a tensor)
@pointwise_dynamic(is_tensor=[True, False], promotion_methods=[(0, 1, "INT_TO_FLOAT")])
@triton.jit
def shifted_chebyshev_polynomial_u_kernel_scalar_n(x, n):
    # Same as above but n is a scalar
    x_f32 = x.to(tl.float32)
    n_f32 = n.to(tl.float32)

    x_shifted = x_f32 * 2.0 - 1.0

    x_shifted = tl.where(x_shifted > 1.0, 1.0, x_shifted)
    x_shifted = tl.where(x_shifted < -1.0, -1.0, x_shifted)

    acos_val = tl_extra_shim.acos(x_shifted)
    sin_acos = tl_extra_shim.sin(acos_val)

    near_boundary = tl.abs(sin_acos) < 1e-6

    n_mod_2 = n_f32 - 2.0 * tl_extra_shim.floor(n_f32 / 2.0)
    is_odd = tl.abs(n_mod_2 - 1.0) < 0.5

    boundary_val = tl.where(
        x_shifted < 0.0, tl.where(is_odd, -1.0 - n_f32, n_f32 + 1.0), n_f32 + 1.0
    )

    numerator = tl_extra_shim.sin((n_f32 + 1.0) * acos_val)
    result = numerator / sin_acos

    result = tl.where(near_boundary, boundary_val, result)

    return result.to(x.dtype)


def special_shifted_chebyshev_polynomial_u(x, n):
    logger.debug("GEMS SPECIAL_SHIFTED_CHEBYSHEV_POLYNOMIAL_U")
    # shifted_chebyshev_polynomial_u_cuda only supports float32
    if x.dtype not in (torch.float32,):
        raise ValueError(f"Unsupported dtype {x.dtype}, only float32 is supported")
    # Handle scalar n
    if not isinstance(n, torch.Tensor):
        return shifted_chebyshev_polynomial_u_kernel_scalar_n(x, n)
    return shifted_chebyshev_polynomial_u_kernel(x, n)


def special_shifted_chebyshev_polynomial_u_(x, n):
    logger.debug("GEMS SPECIAL_SHIFTED_CHEBYSHEV_POLYNOMIAL_U_")
    # shifted_chebyshev_polynomial_u_cuda only supports float32
    if x.dtype not in (torch.float32,):
        raise ValueError(f"Unsupported dtype {x.dtype}, only float32 is supported")
    if not isinstance(n, torch.Tensor):
        return shifted_chebyshev_polynomial_u_kernel_scalar_n(x, n, out0=x)
    return shifted_chebyshev_polynomial_u_kernel(x, n, out0=x)
