# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.utils import pointwise_dynamic

logger = logging.getLogger(__name__)


# Shared H_n(x) computation for degree n in [0, 9].
# Physicist's Hermite polynomial: H_0(x)=1, H_1(x)=2x,
# H_{n+1}(x) = 2*x*H_n(x) - H_{n-1}(x).
# Evaluated in float32 for numerical stability.
@triton.jit
def _hermite_Hn(x, n_int):
    xf = x.to(tl.float32)

    # H_0(x) = 1
    h0: tl.float32 = 1.0
    # H_1(x) = 2*x
    h1: tl.float32 = 2.0 * xf
    # H_2(x) = 4*x^2 - 2
    x2 = xf * xf
    h2: tl.float32 = 4.0 * x2 - 2.0
    # H_3(x) = 8*x^3 - 12*x
    x3 = x2 * xf
    h3: tl.float32 = 8.0 * x3 - 12.0 * xf
    # H_4(x) = 16*x^4 - 48*x^2 + 12
    x4 = x2 * x2
    h4: tl.float32 = 16.0 * x4 - 48.0 * x2 + 12.0
    # H_5(x) = 32*x^5 - 160*x^3 + 120*x
    x5 = x4 * xf
    h5: tl.float32 = 32.0 * x5 - 160.0 * x3 + 120.0 * xf
    # H_6(x) = 64*x^6 - 480*x^4 + 720*x^2 - 120
    x6 = x3 * x3
    h6: tl.float32 = 64.0 * x6 - 480.0 * x4 + 720.0 * x2 - 120.0
    # H_7(x) = 128*x^7 - 1344*x^5 + 3360*x^3 - 1680*x
    x7 = x6 * xf
    h7: tl.float32 = 128.0 * x7 - 1344.0 * x5 + 3360.0 * x3 - 1680.0 * xf
    # H_8(x) = 256*x^8 - 3584*x^6 + 13440*x^4 - 13440*x^2 + 1680
    x8 = x4 * x4
    h8: tl.float32 = 256.0 * x8 - 3584.0 * x6 + 13440.0 * x4 - 13440.0 * x2 + 1680.0
    # H_9(x) = 512*x^9 - 9216*x^7 + 48384*x^5 - 80640*x^3 + 30240*x
    x9 = x8 * xf
    h9: tl.float32 = (
        512.0 * x9 - 9216.0 * x7 + 48384.0 * x5 - 80640.0 * x3 + 30240.0 * xf
    )

    # Select H_n based on padded-n value (n_int in [0, 9])
    result: tl.float32 = h0
    result = tl.where(n_int == 1, h1, result)
    result = tl.where(n_int == 2, h2, result)
    result = tl.where(n_int == 3, h3, result)
    result = tl.where(n_int == 4, h4, result)
    result = tl.where(n_int == 5, h5, result)
    result = tl.where(n_int == 6, h6, result)
    result = tl.where(n_int == 7, h7, result)
    result = tl.where(n_int == 8, h8, result)
    result = tl.where(n_int == 9, h9, result)

    return result


@pointwise_dynamic(promotion_methods=[(0, 1, "DEFAULT")])
@triton.jit
def hermite_polynomial_h_func(x, n):
    n_int = n.to(tl.int32)
    result = _hermite_Hn(x, n_int)
    return result.to(x.dtype)


def special_hermite_polynomial_h_tensor_tensor(x, n):
    logger.debug("GEMS SPECIAL_HERMITE_POLYNOMIAL_H")
    return hermite_polynomial_h_func(x, n)


@pointwise_dynamic(is_tensor=[True, False], promotion_methods=[(0, 1, "DEFAULT")])
@triton.jit
def hermite_polynomial_h_func_tensor_scalar(x, n):
    n_int = n.to(tl.int32)
    result = _hermite_Hn(x, n_int)
    return result.to(x.dtype)


def special_hermite_polynomial_h(x, n):
    logger.debug("GEMS SPECIAL_HERMITE_POLYNOMIAL_H")
    if x.dtype not in (torch.float32, torch.float64):
        raise ValueError(f"Unsupported dtype {x.dtype}")

    # Validate n is in supported range [0, 9]
    if isinstance(n, torch.Tensor):
        n_int = n.to(torch.int32)
        n_min = n_int.min().item()
        n_max = n_int.max().item()
        if n_min < 0 or n_max > 9:
            raise ValueError(
                f"special_hermite_polynomial_h only supports n in [0, 9], "
                f"got n in [{n_min}, {n_max}]"
            )
    elif isinstance(n, (int, float)):
        if int(n) < 0 or int(n) > 9:
            raise ValueError(
                f"special_hermite_polynomial_h only supports n in [0, 9], got n={n}"
            )

    if isinstance(x, torch.Tensor) and isinstance(n, torch.Tensor):
        return hermite_polynomial_h_func(x, n)
    elif isinstance(x, torch.Tensor):
        return hermite_polynomial_h_func_tensor_scalar(x, n)
    else:
        raise ValueError("First argument must be a tensor")
