# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems import runtime
from flag_gems.runtime import torch_device_fn
from flag_gems.utils import libentry
from flag_gems.utils import triton_lang_extension as tle

logger = logging.getLogger(__name__)


@libentry()
@triton.jit
def small_n_log_softmax_kernel(
    output_ptr,
    input_ptr,
    M,
    N,
    stride_m,
    BLOCK_N: tl.constexpr,
):
    """Kernel for small N (N <= 1024): single warp, single pass scan."""
    row_id = tl.program_id(0)
    col_offsets = tl.arange(0, BLOCK_N)
    mask = col_offsets < N

    # Load the entire row in one go
    row = tl.load(
        input_ptr + row_id * stride_m + col_offsets, mask=mask, other=-float("inf")
    ).to(tl.float32)

    # Single pass: compute max, then exp and sum
    row_max = tl.max(row, axis=0)
    row_shifted = row - row_max
    exp_row = tl.exp(row_shifted)
    sum_exp = tl.sum(exp_row, axis=0)
    log_sum = tl.log(sum_exp)
    out = row_shifted - log_sum

    # Store result
    tl.store(output_ptr + row_id * stride_m + col_offsets, out, mask=mask)


@libentry()
@triton.autotune(
    configs=runtime.get_tuned_config("log_softmax"),
    key=["M", "N"],
)
@triton.jit
def large_n_log_softmax_kernel(
    output_ptr,
    input_ptr,
    M,
    N,
    K,
    BLOCK_M: tl.constexpr = 8,
    BLOCK_N: tl.constexpr = 256,
):
    """Kernel for large N (N > 1024): two-pass online softmax algorithm."""
    pid_m = tle.program_id(0)
    pid_k = tle.program_id(1)
    m_offset = pid_m * BLOCK_M + tl.arange(0, BLOCK_M)

    # First pass: compute max and sum of exp
    m = tl.full([BLOCK_M, BLOCK_N], value=float("-inf"), dtype=tl.float32)
    z = tl.full([BLOCK_M, BLOCK_N], value=0.0, dtype=tl.float32)
    for start_n in range(0, N, BLOCK_N):
        n_offset = start_n + tl.arange(0, BLOCK_N)
        offset = m_offset[:, None] * N * K + n_offset[None, :] * K + pid_k
        mask = (m_offset[:, None] < M) & (n_offset[None, :] < N)
        input_ptrs = input_ptr + offset
        inp = tl.load(input_ptrs, mask=mask, other=-float("inf")).to(tl.float32)
        m_new = tl.maximum(inp, m)
        all_neg_inf = m_new == float("-inf")
        z = tl.where(all_neg_inf, z, z * tl.exp(m - m_new) + tl.exp(inp - m_new))
        m = m_new

    m_reduced = tl.max(m, 1)
    z = tl.sum(z * tl.exp(m - m_reduced[:, None]), 1)
    m = m_reduced

    # Second pass: compute and store output
    for start_n in range(0, N, BLOCK_N):
        n_offset = start_n + tl.arange(0, BLOCK_N)
        offset = m_offset[:, None] * N * K + n_offset[None, :] * K + pid_k
        mask = (m_offset[:, None] < M) & (n_offset[None, :] < N)
        input_ptrs = input_ptr + offset
        inp = tl.load(input_ptrs, mask=mask, other=-float("inf")).to(tl.float32)
        o = inp - m[:, None] - tl.log(z[:, None])
        tl.store(output_ptr + offset, o, mask=mask)


def special_log_softmax(self, dim, dtype=None):
    logger.debug("GEMS SPECIAL_LOG_SOFTMAX")

    assert dim >= -self.ndim and dim < self.ndim, "Invalid dim"
    dim = dim % self.ndim

    M = 1
    N = self.shape[dim]
    for i in range(dim):
        M *= self.shape[i]

    inp = self.contiguous()

    # Handle dtype conversion
    if dtype is not None and dtype != inp.dtype:
        inp = inp.to(dtype)

    dtype = inp.dtype
    out = torch.empty_like(inp, dtype=dtype)
    K = inp.numel() // M // N

    # Dual-path: small N uses single-warp kernel, large N uses two-pass kernel
    with torch_device_fn.device(inp.device):
        if N <= 1024:
            # Small N: single warp kernel
            # For dim=1 (most common case with contiguous tensor), stride is stride(0)
            # For dim=0, stride is stride(1) which is the full row stride
            BLOCK_N = triton.next_power_of_2(N)
            grid = (M * K,)
            # Get the stride of dimension that's one step after the reduction dim
            # For contiguous tensor, this is inp.stride(dim - 1) when dim > 0
            # For dim=1, this is inp.stride(0) = shape[1]
            row_stride = inp.stride(dim - 1) if dim > 0 else inp.stride(inp.ndim - 1)
            small_n_log_softmax_kernel[grid](
                out,
                inp,
                M,
                N,
                row_stride,
                BLOCK_N=BLOCK_N,
            )
        else:
            # Large N: two-pass online softmax kernel with autotune
            grid = lambda meta: (
                triton.cdiv(M, meta["BLOCK_M"]),
                K,
            )
            large_n_log_softmax_kernel[grid](
                out,
                inp,
                M,
                N,
                K,
            )

    return out
