# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging
from typing import List

import torch
import triton
import triton.language as tl

from flag_gems import runtime

logger = logging.getLogger(__name__)


@triton.autotune(
    configs=runtime.get_tuned_config("unbind_copy"),
    key=["num_elements"],
)
@triton.jit
def unbind_copy_kernel(
    input_ptr,
    output_ptr,
    dim_size,
    dim_prod_post,
    num_elements,
    BLOCK_SIZE: tl.constexpr,
):
    """Kernel for unbind_copy.

    Uses 2D grid: (num_blocks, dim_size)
    - program_id(0): block index within one output tensor
    - program_id(1): which output tensor (slice) to copy
    """
    pid_x = tl.program_id(0)
    slice_id = tl.program_id(1)

    block_start = pid_x * BLOCK_SIZE
    offsets = tl.arange(0, BLOCK_SIZE)
    mask = block_start + offsets < num_elements

    idx = block_start + offsets

    # Compute indices in the output tensor
    pre_idx = idx // dim_prod_post
    post_idx = idx % dim_prod_post

    # Compute the flat index in the input tensor
    input_flat_idx = (
        pre_idx * dim_size * dim_prod_post + slice_id * dim_prod_post + post_idx
    )

    # Load from input
    data = tl.load(input_ptr + input_flat_idx, mask=mask)

    # Store to output - each slice has its own contiguous storage
    # output is a pointer to the start of the output storage
    # We need to compute offset for each slice
    slice_offset = slice_id * num_elements
    tl.store(output_ptr + slice_offset + idx, data, mask=mask)


def unbind_copy(input: torch.Tensor, dim: int = 0) -> List[torch.Tensor]:
    """Unbind a tensor into a list of tensors.

    Removes a tensor dimension and returns a tuple of all the slices along
    that dimension. Unlike torch.unbind, this function creates new copies
    of the data rather than views.

    Args:
        input: The tensor to unbind
        dim: The dimension along which to unbind

    Returns:
        A list of tensors
    """
    logger.debug("GEMS UNBIND_COPY")

    if dim < 0:
        dim = dim + input.ndim

    if dim < 0 or dim >= input.ndim:
        raise IndexError(
            f"Dimension out of range (expected to be in range of [{-input.ndim}, {input.ndim - 1}], but got {dim})"
        )

    num_slices = input.shape[dim]
    if num_slices == 0:
        return []

    # Get the shape of each output tensor (without the unbind dimension)
    output_shape = list(input.shape)
    del output_shape[dim]

    # Create a single contiguous output storage for all slices
    # Then we'll slice this storage to get individual output tensors
    num_elements_per_slice = 1
    for s in output_shape:
        num_elements_per_slice *= s

    if num_elements_per_slice == 0:
        # Return empty list of outputs
        return [
            torch.empty(output_shape, dtype=input.dtype, device=input.device)
            for _ in range(num_slices)
        ]

    # Total storage needed
    total_elements = num_slices * num_elements_per_slice
    output_storage = torch.empty(
        (total_elements,), dtype=input.dtype, device=input.device
    )

    # Compute stride products
    dim_prod_post = 1
    for i in range(dim + 1, input.ndim):
        dim_prod_post *= input.shape[i]

    # Make input contiguous for simpler indexing
    input = input.contiguous()

    # Use 2D grid: (num_blocks_per_slice, num_slices)
    BLOCK = 1024
    grid_x = triton.cdiv(num_elements_per_slice, BLOCK)
    grid = (grid_x, num_slices)

    unbind_copy_kernel[grid](
        input,
        output_storage,
        num_slices,
        dim_prod_post,
        num_elements_per_slice,
    )

    # Now split the storage into individual output tensors
    outputs = []
    for i in range(num_slices):
        start = i * num_elements_per_slice
        end = start + num_elements_per_slice
        outputs.append(output_storage[start:end].reshape(output_shape))

    return outputs
