name: cpp-ops

permissions:
  contents: read

on:
  workflow_call:

jobs:
  test:
    runs-on: h20
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        continue-on-error: true
      - uses: ./.github/actions/checkout-retry
      - uses: ./.github/actions/setup-flaggems
        with:
          vendor: nvidia
          gpu_check_script: tools/gpu_check_nvidia.sh

      - shell: bash
        run: |
          export PATH="/home/secure/.pyenv/bin:/usr/local/cuda/bin:$PATH"
          eval "$(pyenv init -)"
          export CMAKE_ARGS="-DFLAGGEMS_BUILD_C_EXTENSIONS=ON -DCMAKE_BUILD_TYPE=Release"
          pip install -v -e . --no-build-isolation
      - shell: bash
        run: |
          export PATH="/home/secure/.pyenv/bin:/usr/local/cuda/bin:$PATH"
          eval "$(pyenv init -)"
          cd build/cpython-*/ctests
          export FLAGGEMS_SOURCE_DIR=$(python -c "import os;import flag_gems;print(os.path.dirname(flag_gems.__file__))")
          ctest -V
